.gitignore, README.md, circle.yml, eoc_journal/__init__.py, eoc_journal/eoc_journal.py, eoc_journal/public/css/eoc_journal.css, eoc_journal/templates/eoc_journal.html, eoc_journal/utils.py, pylintrc, requirements-test.txt, requirements.txt, run_tests.py, setup.py, tests/integration/test_eoc_journal.py
This implements a very basic XBlock.
Currently it only lets you specify a link to a "Key Takeaways PDF" file that you previously uploaded in the Studio "Files & Uploads" section, and displays a link to it in the LMS.
**Testing**:
1. Install this xblock to your edx-platform virtual environment (`pip install -e .`)
1. Under 'Advanced Settings' in Studio, add `"eoc-journal"` to 'Advanced Module List'.
1. Add a new 'End of Course Journal' to a unit in your course.
1. View the block in the LMS and verify that it says "Key Takeaways PDF not available at this time."
1. Upload a PDF to the Studio 'Files & Uploads' section and store its Studio url handle (it looks like `/static/<myfilename>`)
1. Edit the EOC Journal block in the studio and paste the URL handle into the "Key Takeaways PDF handle" …
=> Initial implementation.

eoc_journal/course_blocks_api.py, eoc_journal/eoc_journal.py, eoc_journal/templates/eoc_journal_edit.html, requirements.txt, setup.py, tests/integration/data/course_api_response.json, tests/integration/test_eoc_journal.py
We are using the edX Course Blocks API to fetch all `pb-answer` blocks in the current course. All `pb-answer` blocks in the course are displayed as labeled checkboxes in the studio edit view. The checkboxes are arranged by section/subsection/unit in the order as they appear in the course.
**Testing**:
1. Add some `pb-answer`(Freeform problem builder questions, also known as Long Answers) blocks to your course. Add them to different sections/units.
1. Add an EOC Journal block to your course.
1. Edit the EOC Journal block in the Studio.
1. Verify that the edit view contains the "Problem Builder Freeform Answers" field, which presents the `pb-answer` blocks from the current course in a checkbox view, allowing you to tick the blocks that you want to select.
1. Tick some checkboxes & save the …
=> Display pb-answer blocks in edit view for staff user to select.

eoc_journal/eoc_journal.py, eoc_journal/public/css/eoc_journal.css, eoc_journal/templates/eoc_journal.html, tests/integration/test_eoc_journal.py
This PR displays the value of `display_name` on the frontend. The `display_name` setting was already configurable in the Studio, but was not displayed on the frontend.
**Testing**:
1. Add a new EOC Journal block to your course.
1. Verify that the default "End Of Course Journal" title is visible in the LMS.
1. Change the title/display_name in the Studio, save & publish.
1. Observe that the modified title is now visible in the LMS.
**Reviewers**:
=> Show title (display_name) in the LMS.

README.md, circle.yml, eoc_journal/course_blocks_api.py, eoc_journal/eoc_journal.py, eoc_journal/templates/eoc_journal.html, eoc_journal/utils.py, requirements.txt, setup.py, tests/integration/test_eoc_journal.py
**Testing instructions**
- Setup a course with pb-answers and eoc-journal
- Mark at least one pb-answer in eoc-journal when running Studio
- Log into Apros, answer the pb-answer created and go to the roc-journal
- Check that you see the selected pb-answer, with the name of the section it belongs to, it's `display_name` and the `student_input`.
The journal should look like the screenshot below.
To run the integration tests, follow the updated instructions in the README (this PR).
Make sure all tests pass.
**Reviewers**
=> Display selected pb-answers in student view

eoc_journal/api_client.py, eoc_journal/eoc_journal.py, eoc_journal/templates/eoc_journal.html, tests/integration/test_eoc_journal.py
Progress would not display in the LMS because we were trying to fetch `'cohort_avg'` instead of `'course_avg'` from the API response, so the xblock was always displaying "Progress data is not available." in the LMS.
This also converts some rounded floats to ints to match the format of metrics displayed in apros.
**Testing**:
1. Verify that without this fix the LMS always says "Progress data is not available."
1. Verify that with this fix, the actual progress data is displayed and matches the values on the apros "progress" page.
**Reviewers**:
=> Fix progress metrics.

README.md, eoc_journal/api_client.py, eoc_journal/eoc_journal.py, eoc_journal/templates/eoc_journal.html, tests/integration/data/grades_leader_metrics_response.json, tests/integration/test_eoc_journal.py
Adds Proficiency metrics to the EOC Journal, as presented by the Gradebook Leaderboard API.
**JIRA tickets**: MCKIN-4999
**Screenshots**:
In Studio:
In Solutions LMS:
**Partner information**: 3rd party-hosted open edX instance
**Testing instructions**:
*Note*: For best results, register new users to perform each of these steps. The demo users created by the Solutions devstack don't have `UserProfile` entries, and so the EOC Journal XBlock shows errors when these users try to view the units.
In Studio:
1. Create a new course.
1. Under "Advanced Settings", add `"eoc-journal"`.
1. Add a graded Subsection, with one or more problems in it.
1. Add a unit containing an EOC Journal component.
1. Note that the "Proficiency" section shows the following text in Studio:
```
Proficiency data is not …
```
=> Adds Proficiency metrics taken from the Gradebook Leaderboard API

eoc_journal/eoc_journal.py, eoc_journal/templates/eoc_journal.html, tests/integration/data/user_engagement_metrics_response.json, tests/integration/test_eoc_journal.py
Incorrect Engagement Metrics
When "Number of Replies you made to other posts" is reported to the user, in the Apros LMS, it's reporting
```python
"total_replies": social["metrics"].num_replies + social["metrics"].num_comments,
```
But in this XBlock, only `num_replies` were being included, resulting in discrepancies between this XBlock and the progress page if the user had commented on other posts.
Testing instructions:
Have/import a course with this XBlock and some discussion forums. Enroll two users in that course. Make some forum posts as one or both of the users, including replies and comments on those replies. Verify that the progress page in apros and this EOC Journal XBlock show the same breakdown of engagement scores.
=> Fix incorrect progress/engagement metrics

eoc_journal/api_client.py, eoc_journal/course_blocks_api.py, eoc_journal/utils.py, tests/integration/test_eoc_journal.py
This PR makes `_get_course method` use JWT authentication as it is required now since https://github.com/edx-solutions/api-integration/pull/102 is merged (and, thus, [CourseDetail](https://github.com/edx-solutions/api-integration/blob/master/edx_solutions_api_integration/courses/views.py#L564) inherits from [MobileAPIView](MobileAPIView)).
**Dependencies**: None
**Screenshots**: n/a
**Sandbox URL**: TBD - sandbox is being provisioned.
**Merge deadline**: None
**Testing instructions**:
1. Run the course with an End of Course Journal Xblock.
2. See it fail on the current master (observe `401` error in the backend console for a GET call to `/api/server/courses/{course_id}?depth=5`).
3. Make devstack use this PR's branch of xblock-eoc-journal.
4. Go again to an End of Course Journal Xblock …
=> Make _get_course method use JWT authentication.

circle.yml
Migrating to CircleCI version 2.
JIRA Ticket: OC-4151
Testing instructions:
Check that tests are passing.
Note to reviewer:
Added Cache, so that it doesn't have to install requirements each time.
=> Migrate to CircleCI v2 

README.md, eoc_journal/eoc_journal.py, eoc_journal/templates/eoc_journal.html, tests/integration/test_eoc_journal.py
Adds the ability to customise the link text and title for the PDF Report link. 
**Reviewer:**
=> MCKIN-7791 Allow customising PDF report link tile and text

eoc_journal/eoc_journal.py, eoc_journal/public/js/eoc_journal.js
Sends an event to Google Analytics (if configured) when a learner clicks on either the 
"PDF Report" or "Key Takeaways" download links displayed by this xblock.
**Screenshots**
EOC Journal XBlock GUI (unchanged):
Google analytics screen showing events received for these events:
**Testing instructions**
1. Create a course with a subsection containing a Problem Builder Long answer, and an EOC Journal unit, e.g. [MCKIN-7788.ooVv6d.tar.gz](https://github.com/open-craft/xblock-eoc-journal/files/2147388/MCKIN-7788.ooVv6d.tar.gz)
Ensure that a Key Takeaways PDF is provided, and/or the EOC unit is linked to the Problem Builder long answer problem.
* View the PB unit in Studio, LMS, or Apros, and complete the long answer problem.
This allows the EOC XBlock to show the "PDF Report" download link.
* …
=> MCKIN-7788 Adds Google Analytics click handlers to PDF download links

eoc_journal/eoc_journal.py, eoc_journal/templates/eoc_journal.html, tests/integration/test_eoc_journal.py
Add options in Edit view in studio to hide metrics, key takeaways and free text answers from student view.
**Testing instructions**
1. Create a course with a subsection containing a Problem Builder Long answer, and an EOC Journal unit.
2. Check that by default only _PDF Report Download_ section is visible.
3. Set newly-added options in Studio, namely:
- `Display User Metrics`
- `Display Key Takeaways section`
- `Display answers`
and click Publish on the Unit in Studio. Assure metrics section, key takeaways section and free-text answers section are visible now.
4. Click on _Download PDF now_ and see that PDF contains only free-text answers and doesn't contain metrics section and key takeaways section (in one of the comments on the ticket, it was suggested that PDF should contain only …
=> MCKIN-7789: Add option to hide metrics, key takeaways and free text answers from student view.

eoc_journal/eoc_journal.py, eoc_journal/pdf_generator.py, pylintrc, tests/integration/test_eoc_journal.py
This PR contains 3 different enhancements:
- [Horizantal line between questions](https://github.com/open-craft/xblock-eoc-journal/commit/b6f987ece461d2d5de715769c0ae3609fa1fc085):
Appears on all generated reports and there's no custom setting or flow controls it.
- [Default PDF header to Course Title](https://github.com/open-craft/xblock-eoc-journal/commit/6cd863e9b4ae2a5a4d54c90fb047d52229b66dc9):
Changes made on the `display_name` field where it's now left blank to determine whether to use the Course Title or another custom value.
- [Use custom fonts in generated PDF reports](https://github.com/open-craft/xblock-eoc-journal/commit/7ea5cc69ec341d15d6147b7842efd7048615dcf7):
Users now can specify a url to the desired font and we will generate the report using it. The font can be hosted …
=> Enhancements on the freeform-answers report

eoc_journal/eoc_journal.py, tests/integration/data/course_api_response.json, tests/integration/test_eoc_journal.py
A recent PR (https://github.com/open-craft/xblock-eoc-journal/pull/13) added support for stripping HTML tags from the question text when rendering in the Course Journal. This inadvertently made it an error to have empty question test, or question text that contains broken content that would cause a parsing error. 
This PR fixes that by falling back to the original question text in case of a parsing error. 
**Testing instructions:**
1. Create a course that uses the eoc-journal.
2. Add a problem-builder long-form question that has no question text.
3. Include this question in the list of questions for the course journal. 
4. As a student submit an answer for a problem that has not question text. 
5. Visit the page with the course journal. It should not throw an error.
=> Allow questions to be empty or invalid XML/HTML

.gitignore, circle.yml, eoc_journal/eoc_journal.py, requirements-test.txt, tests/integration/data/course_api_response.json
Fix issue where questions in the journal would not appear in the same order as in the course.
**JIRA tickets**: MCKIN-8326 / BEBOP-152
**Reviewers**
=> [MCKIN-8326] [BEBOP-152] Fix question ordering bug

eoc_journal/completion_api.py
The Xblock shouldn't crash when completionapi returns a 404, rather it should return a None value
=> BB-516 handle completionapi 404

eoc_journal/eoc_journal.py, requirements-test.txt, setup.py, tests/unit/test_import.py
The EOC uses the [block id](https://github.com/open-craft/xblock-eoc-journal/blob/master/eoc_journal/eoc_journal.py#L354) to [keep track](https://github.com/open-craft/xblock-eoc-journal/blob/master/eoc_journal/eoc_journal.py#L58) of the selected problems to appear in the journal.
The block id is essentially the [block location](https://github.com/open-craft/xblock-eoc-journal/blob/master/tests/integration/test_eoc_journal.py#L53) which is bound to a specific course name.
This PR uses [`UsageKey.map_into_course` method](https://github.com/edx/opaque-keys/blob/master/opaque_keys/edx/keys.py#L95) to re-map each block location key to the target course id when importing a course. This is done by overriding [`parse_xml` xblock method](https://github.com/edx/XBlock/blob/master/xblock/mixins.py#L …
=> BB-1126 Map block ids into correct course ids when importing XML

eoc_journal/compat.py, eoc_journal/utils.py, requirements-test.txt, setup.py
Problem root cause: JwtBuilder class was removed in commit dc56a63e of edx-platform
git repository and the eoc-journal xblock was not updated accordingly.
=> [BB-2132] [YONK-1560] Support JWT creation on openedx ironwood

eoc_journal/eoc_journal.py, setup.py
If a specific language course's language translation doesn't exists then load the default 'en' language's js file to prevent a 404 error.
=> MCKIN-23098 404 error on opening the module having EOC with no translations integrated

eoc_journal/api_client.py, eoc_journal/base_api_client.py, eoc_journal/completion_api.py, eoc_journal/course_blocks_api.py, eoc_journal/utils.py, setup.py
EdxRestApiClient is deprecated since it's based on slumber which is no longer supported. It is also throwing errors on Python 3. 
This PR switches to using JWT directly with the requests library for API requests. 
**Testing Instructions**
- Install the PR version of this XBlock
- Enable all features of the block in studio. 
- Make sure the block works in the LMS. 
- Ensure that it reports the same results as Apros.
=> [MCKIN-24505] [BB-2993] Switch to using plain requests and remove depricated EdxRestApiClient

circle.yml, requirements.txt, setup.py
This PR fixes the following import error that appeared due to the latest version of ``reportlab`` - 
```
ImportError: reportlab requires Python 2.7+ or 3.6+; other versions are unsupported.
```
**JIRA tickets**: https://tasks.opencraft.com/browse/BB-3164
**Discussions**: N/A
**Dependencies**: None
~~**Screenshots**:~~ 
~~**Sandbox URL**:~~
**Merge deadline**: ASAP
**Testing instructions**:
1. Install this PR version to a devstack in both LMS and studio
2. Enable xblock-eoc-journal from studio
3. Studio and LMS should work correctly without any import error
**Author notes and concerns**:
1. Using ``setup.py`` for specifying dependency version instead of ``requirements.txt``, so that it stays same while installing from ``requirements.txt`` or via ``pip install -e .`` command
**Reviewers** …
=> [BB-3164] [MCKIN-27010] Fix import error in eoc-journal

requirements-test.txt, setup.py
Juniper release installs version` 5.2.1` of `edx-rest-api-client`. Because this repo has `edx-rest-api-client` pinned to `1.9.2` it raises a build error on platform. 
`ERROR: xblock-eoc-journal 0.10.0 has requirement edx-rest-api-client==1.9.2, but you'll have edx-rest-api-client 5.2.1 which is incompatible.
`
=> MCKIN-32454: use edx-rest-api-client >= 5.2.1 to match juniper and higher releases
